name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Chzeckout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Build Docker image
        run: docker build -t httpreplica:latest .

      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Docker image
        run: docker tag httpreplica:latest ${{ secrets.DOCKER_USERNAME }}/httpreplica:latest

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/httpreplica:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker stop my-app || true
            docker rm my-app || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/httpreplica:latest
            docker run -d --name httpreplica -p 50050:50050 ${{ secrets.DOCKER_USERNAME }}/httpreplica:latest
